version: '2'
services:
  eureka-server:
    build:
      context: ./Eureka
      dockerfile: Dockerfile
    image: eureka-server-image
    ports:
      - "8081:8081"
  api-gateway:
    build:
      context: ./APIgateway
      dockerfile: Dockerfile
    image: api-gateway-image
    ports:
      - "8080:8080"
  activity-server:
    build:
      context: ./ActivityService
      dockerfile: Dockerfile
    image: activity-server-image
    ports:
      - "8082:8082"
  user-server:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    image: user-server-image
    ports:
      - "8081:8081"
  newsfeed-server:
    build:
      context: ./NewsFeedService
      dockerfile: Dockerfile
    image: newsfeed-server-image
    ports:
      - "8083:8083"
  user-db:
    image: mysql:8.0.36
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tockbit
  activity-db:
    image: mysql:8.0.36
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: activitydb
  newsfeed-db:
    image: mysql:8.0.36
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: newsfeeddb
