server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/auth/**
        - id: activity-service
          uri: lb://activity-service
          predicates:
            - Path=/act/**
        - id: newsfeed-service
          uri: lb://newsfeed-service
          predicates:
            - Path=/newsfeed

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
